# Generated by Django 6.0.3 on 2026-03-11 10:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_key",
                    models.CharField(
                        help_text="ISO week key, e.g. 2026-W11", max_length=10
                    ),
                ),
                ("week_start", models.DateField(blank=True, null=True)),
                ("week_end", models.DateField(blank=True, null=True)),
                (
                    "total_load",
                    models.IntegerField(help_text="Sum of event weights this week"),
                ),
                ("threshold", models.IntegerField(default=7)),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        default="warning",
                        max_length=20,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("weekly_overload", "Weekly Overload"),
                            ("daily_overload", "Daily Overload"),
                            ("exam_collision", "Exam Collision"),
                            ("consecutive_overload", "Consecutive Overload"),
                        ],
                        default="weekly_overload",
                        max_length=30,
                    ),
                ),
                ("courses_affected", models.JSONField(default=list)),
                ("message", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["week_key"],
                "unique_together": {("week_key", "conflict_type")},
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. CS101 - Introduction to CS", max_length=200
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, help_text="e.g. CS101", max_length=20),
                ),
                ("professor", models.CharField(blank=True, max_length=200)),
                (
                    "semester",
                    models.CharField(
                        blank=True, help_text="e.g. Spring 2026", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_events", models.IntegerField(default=0)),
                ("total_conflicts", models.IntegerField(default=0)),
                ("max_weekly_load", models.IntegerField(default=0)),
                ("avg_weekly_load", models.FloatField(default=0.0)),
                ("summary_json", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("courses", models.ManyToManyField(blank=True, to="syllabus.course")),
            ],
        ),
        migrations.CreateModel(
            name="SyllabusFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="syllabi/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "txt", "docx"]
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="Size in bytes"),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, help_text="Raw extracted text"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_files",
                        to="syllabus.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("homework", "Homework"),
                            ("assignment", "Assignment"),
                            ("quiz", "Quiz"),
                            ("presentation", "Presentation"),
                            ("project", "Project"),
                            ("midterm", "Midterm"),
                            ("exam", "Exam"),
                            ("final", "Final Exam"),
                            ("lab", "Lab"),
                            ("reading", "Reading"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "workload",
                    models.IntegerField(default=1, help_text="Workload weight (1-8)"),
                ),
                (
                    "raw_line",
                    models.TextField(
                        blank=True, help_text="Original line from syllabus"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Human verified event"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="syllabus.course",
                    ),
                ),
                (
                    "syllabus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="syllabus.syllabusfile",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "workload"],
                "indexes": [
                    models.Index(fields=["date"], name="syllabus_ev_date_122ac3_idx"),
                    models.Index(
                        fields=["course", "date"], name="syllabus_ev_course__69ce2d_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="syllabus_ev_event_t_490b97_idx"
                    ),
                ],
            },
        ),
    ]
